################################################################################
#
# toolchain-external-wasi-sdk
#
################################################################################

TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION = 30.0
TOOLCHAIN_EXTERNAL_WASI_SDK_SITE = https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30
TOOLCHAIN_EXTERNAL_WASI_SDK_PKGDIR = toolchain/toolchain-external/toolchain-external-wasi-sdk

ifeq ($(HOSTARCH),aarch64)
TOOLCHAIN_EXTERNAL_WASI_SDK_SOURCE = wasi-sdk-$(TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION)-arm64-linux.tar.gz
else
TOOLCHAIN_EXTERNAL_WASI_SDK_SOURCE = wasi-sdk-$(TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION)-x86_64-linux.tar.gz
endif

TOOLCHAIN_EXTERNAL_WASI_SDK_STRIP_COMPONENTS = 1

# Create GCC-compatible symlinks in the extract dir so they get moved
# along with everything else by TOOLCHAIN_EXTERNAL_MOVE.
define TOOLCHAIN_EXTERNAL_WASI_SDK_CREATE_SYMLINKS
	cd $(@D)/bin && \
	for tool in gcc cc; do \
		ln -sf wasm32-wasi-clang wasm32-wasi-$$tool; \
	done && \
	for tool in g++ c++; do \
		ln -sf wasm32-wasi-clang++ wasm32-wasi-$$tool; \
	done && \
	for tool in ar nm objcopy objdump ranlib strip size strings readelf; do \
		[ -f llvm-$$tool ] && ln -sf llvm-$$tool wasm32-wasi-$$tool || \
		[ -f $$tool ] && ln -sf $$tool wasm32-wasi-$$tool || true; \
	done && \
	ln -sf wasm-ld wasm32-wasi-ld && \
	ln -sf clang wasm32-wasi-cpp
endef
TOOLCHAIN_EXTERNAL_WASI_SDK_POST_EXTRACT_HOOKS += TOOLCHAIN_EXTERNAL_WASI_SDK_CREATE_SYMLINKS

$(eval $(toolchain-external-package))

# Override commands generated by toolchain-external-package.
# The stock commands perform GCC-specific validation (gcc --version,
# kernel headers, musl version, SSP) and install GCC sysroot layouts.
# For wasi-sdk (clang-based), we only verify the cross-compiler exists
# and copy the wasi-sysroot.

define TOOLCHAIN_EXTERNAL_WASI_SDK_CONFIGURE_CMDS
	$(Q)$(call check_cross_compiler_exists,$(TOOLCHAIN_EXTERNAL_CC))
endef

define TOOLCHAIN_EXTERNAL_WASI_SDK_BUILD_CMDS
	$(TOOLCHAIN_WRAPPER_BUILD)
endef

# Install wasi-sysroot into staging. The skeleton creates lib/bin/sbin
# as symlinks to usr/*, but wasi-sysroot has real lib/ and include/
# directories. Remove conflicting symlinks before copying. Then install
# POSIX stub headers for APIs not in wasi-libc (netdb, pwd, grp, etc.)
# so packages like busybox can compile.
#
# After sysroot install, patch libc.a and libwasi-emulated-signal.a to
# remove/replace objects that conflict with the wasivm kernel host imports.
# Without these patches, wasi-libc maintains internal state (signal
# handlers, exit paths, CWD tracking) that bypasses the kernel.
define TOOLCHAIN_EXTERNAL_WASI_SDK_INSTALL_STAGING_CMDS
	$(TOOLCHAIN_WRAPPER_INSTALL)
	$(Q)for d in lib include share; do \
		if [ -L $(STAGING_DIR)/$$d ]; then rm -f $(STAGING_DIR)/$$d; fi; \
	done
	$(Q)cp -a $(TOOLCHAIN_EXTERNAL_INSTALL_DIR)/share/wasi-sysroot/* $(STAGING_DIR)/
	$(Q)cp -a $(TOPDIR)/$(TOOLCHAIN_EXTERNAL_WASI_SDK_PKGDIR)/wasi-stubs/* \
		$(STAGING_DIR)/include/wasm32-wasi/
	$(TOOLCHAIN_EXTERNAL_INSTALL_WRAPPER)
	$(call wasi_sdk_patch_libc)
endef

define TOOLCHAIN_EXTERNAL_WASI_SDK_INSTALL_TARGET_CMDS
endef

# Patch wasi-libc static libraries for wasivm kernel compatibility.
#
# wasi-libc objects patched in libc.a:
#   fcntl.c.obj   - replaced: forwards to env.__posix_fcntl3
#                   (wasi-libc only handles F_GETFL/F_SETFL)
#   chdir.c.obj   - removed: env.chdir handles kernel CWD
#   abort.c.obj   - removed: env.abort delivers SIGABRT cleanly
#   exit.c.obj    - replaced: fflush(NULL) + env.__posix_exit (vfork-aware)
#   _Exit.c.obj   - replaced: env.__posix_exit directly
#   pselect.c.obj - replaced: ignore errorfds (WASI has no OOB)
#
# libwasi-emulated-signal.a:
#   signal.c.obj  - removed: env.signal/raise/sigaction via kernel
define wasi_sdk_patch_libc
	$(Q)WASI_LIBC=$(STAGING_DIR)/lib/wasm32-wasi/libc.a; \
	WASI_SIGLIB=$(STAGING_DIR)/lib/wasm32-wasi/libwasi-emulated-signal.a; \
	TMPDIR=$$(mktemp -d); \
	printf '#include <stdarg.h>\nextern int __posix_fcntl3(int fd, int cmd, int arg);\nint fcntl(int fd, int cmd, ...) {\n    __builtin_va_list ap;\n    __builtin_va_start(ap, cmd);\n    int arg = __builtin_va_arg(ap, int);\n    __builtin_va_end(ap);\n    return __posix_fcntl3(fd, cmd, arg);\n}\n' \
		> $$TMPDIR/fcntl.c; \
	$(TARGET_CC) -c -O2 -o $$TMPDIR/fcntl.c.obj $$TMPDIR/fcntl.c; \
	printf 'typedef struct __FILE FILE;\nextern int fflush(FILE *);\nextern void __posix_exit(int status) __attribute__((noreturn));\nvoid exit(int status) {\n    fflush((FILE *)0);\n    __posix_exit(status);\n    __builtin_unreachable();\n}\n' \
		> $$TMPDIR/exit.c; \
	$(TARGET_CC) -c -O2 -o $$TMPDIR/exit.c.obj $$TMPDIR/exit.c; \
	printf 'extern void __posix_exit(int status) __attribute__((noreturn));\nvoid _Exit(int status) {\n    __posix_exit(status);\n    __builtin_unreachable();\n}\n' \
		> $$TMPDIR/_Exit.c; \
	$(TARGET_CC) -c -O2 -o $$TMPDIR/_Exit.c.obj $$TMPDIR/_Exit.c; \
	if [ ! -f "$$WASI_LIBC.orig" ]; then cp "$$WASI_LIBC" "$$WASI_LIBC.orig"; fi; \
	$(TARGET_AR) d "$$WASI_LIBC" fcntl.c.obj 2>/dev/null || true; \
	$(TARGET_AR) r "$$WASI_LIBC" $$TMPDIR/fcntl.c.obj; \
	$(TARGET_AR) d "$$WASI_LIBC" chdir.c.obj 2>/dev/null || true; \
	$(TARGET_AR) d "$$WASI_LIBC" abort.c.obj 2>/dev/null || true; \
	$(TARGET_AR) d "$$WASI_LIBC" exit.c.obj 2>/dev/null || true; \
	$(TARGET_AR) r "$$WASI_LIBC" $$TMPDIR/exit.c.obj; \
	$(TARGET_AR) d "$$WASI_LIBC" _Exit.c.obj 2>/dev/null || true; \
	$(TARGET_AR) r "$$WASI_LIBC" $$TMPDIR/_Exit.c.obj; \
	printf '#include <sys/select.h>\n#include <errno.h>\n#include <limits.h>\n#include <poll.h>\n#include <stddef.h>\nint pselect(int nfds, fd_set *restrict readfds, fd_set *restrict writefds,\n            fd_set *restrict errorfds, const struct timespec *restrict timeout,\n            const sigset_t *sigmask) {\n  if (nfds < 0) { errno = EINVAL; return -1; }\n  fd_set empty; FD_ZERO(&empty);\n  if (readfds == NULL) readfds = &empty;\n  if (writefds == NULL) writefds = &empty;\n  struct pollfd poll_fds[readfds->__nfds + writefds->__nfds];\n  size_t poll_nfds = 0;\n  for (size_t i = 0; i < readfds->__nfds; ++i) {\n    int fd = readfds->__fds[i];\n    if (fd < nfds) {\n      poll_fds[poll_nfds].fd = fd;\n      poll_fds[poll_nfds].events = POLLRDNORM;\n      poll_fds[poll_nfds].revents = 0;\n      poll_nfds++;\n    }\n  }\n  size_t read_count = poll_nfds;\n  for (size_t i = 0; i < writefds->__nfds; ++i) {\n    int fd = writefds->__fds[i];\n    if (fd < nfds) {\n      poll_fds[poll_nfds].fd = fd;\n      poll_fds[poll_nfds].events = POLLWRNORM;\n      poll_fds[poll_nfds].revents = 0;\n      poll_nfds++;\n    }\n  }\n  int poll_timeout;\n  if (timeout) {\n    long long ns = (long long)timeout->tv_sec * 1000000000LL + timeout->tv_nsec;\n    if (ns < 0) { errno = EINVAL; return -1; }\n    long long ms = ns / 1000000;\n    poll_timeout = (ms > INT_MAX) ? INT_MAX : (int)ms;\n  } else {\n    poll_timeout = -1;\n  }\n  if (poll(poll_fds, poll_nfds, poll_timeout) < 0) return -1;\n  FD_ZERO(readfds);\n  FD_ZERO(writefds);\n  for (size_t i = 0; i < poll_nfds; ++i) {\n    struct pollfd *pfd = poll_fds + i;\n    if (i < read_count) {\n      if ((pfd->revents & (POLLRDNORM|POLLIN|POLLHUP|POLLERR)) != 0)\n        readfds->__fds[readfds->__nfds++] = pfd->fd;\n    } else {\n      if ((pfd->revents & (POLLWRNORM|POLLOUT|POLLERR)) != 0)\n        writefds->__fds[writefds->__nfds++] = pfd->fd;\n    }\n  }\n  if (errorfds != NULL) FD_ZERO(errorfds);\n  return readfds->__nfds + writefds->__nfds;\n}\n' \
		> $$TMPDIR/pselect.c; \
	$(TARGET_CC) -c -O2 -o $$TMPDIR/pselect.c.obj $$TMPDIR/pselect.c; \
	$(TARGET_AR) d "$$WASI_LIBC" pselect.c.obj 2>/dev/null || true; \
	$(TARGET_AR) r "$$WASI_LIBC" $$TMPDIR/pselect.c.obj; \
	if [ -f "$$WASI_SIGLIB" ]; then \
		if [ ! -f "$$WASI_SIGLIB.orig" ]; then cp "$$WASI_SIGLIB" "$$WASI_SIGLIB.orig"; fi; \
		$(TARGET_AR) d "$$WASI_SIGLIB" signal.c.obj 2>/dev/null || true; \
	fi; \
	rm -rf $$TMPDIR
endef
