################################################################################
#
# toolchain-external-wasi-sdk
#
################################################################################

TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION = 30.0
TOOLCHAIN_EXTERNAL_WASI_SDK_SITE = https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30
TOOLCHAIN_EXTERNAL_WASI_SDK_PKGDIR = toolchain/toolchain-external/toolchain-external-wasi-sdk

ifeq ($(HOSTARCH),aarch64)
TOOLCHAIN_EXTERNAL_WASI_SDK_SOURCE = wasi-sdk-$(TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION)-arm64-linux.tar.gz
else
TOOLCHAIN_EXTERNAL_WASI_SDK_SOURCE = wasi-sdk-$(TOOLCHAIN_EXTERNAL_WASI_SDK_VERSION)-x86_64-linux.tar.gz
endif

TOOLCHAIN_EXTERNAL_WASI_SDK_STRIP_COMPONENTS = 1

# Create GCC-compatible symlinks in the extract dir so they get moved
# along with everything else by TOOLCHAIN_EXTERNAL_MOVE.
define TOOLCHAIN_EXTERNAL_WASI_SDK_CREATE_SYMLINKS
	cd $(@D)/bin && \
	for tool in gcc cc; do \
		ln -sf wasm32-wasi-clang wasm32-wasi-$$tool; \
	done && \
	for tool in g++ c++; do \
		ln -sf wasm32-wasi-clang++ wasm32-wasi-$$tool; \
	done && \
	for tool in ar nm objcopy objdump ranlib strip size strings readelf; do \
		[ -f llvm-$$tool ] && ln -sf llvm-$$tool wasm32-wasi-$$tool || \
		[ -f $$tool ] && ln -sf $$tool wasm32-wasi-$$tool || true; \
	done && \
	ln -sf wasm-ld wasm32-wasi-ld && \
	ln -sf clang wasm32-wasi-cpp
endef
TOOLCHAIN_EXTERNAL_WASI_SDK_POST_EXTRACT_HOOKS += TOOLCHAIN_EXTERNAL_WASI_SDK_CREATE_SYMLINKS

$(eval $(toolchain-external-package))

# Override commands generated by toolchain-external-package.
# The stock commands perform GCC-specific validation (gcc --version,
# kernel headers, musl version, SSP) and install GCC sysroot layouts.
# For wasi-sdk (clang-based), we only verify the cross-compiler exists
# and copy the wasi-sysroot.

define TOOLCHAIN_EXTERNAL_WASI_SDK_CONFIGURE_CMDS
	$(Q)$(call check_cross_compiler_exists,$(TOOLCHAIN_EXTERNAL_CC))
endef

define TOOLCHAIN_EXTERNAL_WASI_SDK_BUILD_CMDS
	$(TOOLCHAIN_WRAPPER_BUILD)
endef

# Install wasi-sysroot into staging. The skeleton creates lib/bin/sbin
# as symlinks to usr/*, but wasi-sysroot has real lib/ and include/
# directories. Remove conflicting symlinks before copying. Then install
# POSIX stub headers for APIs not in wasi-libc (netdb, pwd, grp, etc.)
# so packages like busybox can compile.
define TOOLCHAIN_EXTERNAL_WASI_SDK_INSTALL_STAGING_CMDS
	$(TOOLCHAIN_WRAPPER_INSTALL)
	$(Q)for d in lib include share; do \
		if [ -L $(STAGING_DIR)/$$d ]; then rm -f $(STAGING_DIR)/$$d; fi; \
	done
	$(Q)cp -a $(TOOLCHAIN_EXTERNAL_INSTALL_DIR)/share/wasi-sysroot/* $(STAGING_DIR)/
	$(Q)cp -a $(TOPDIR)/$(TOOLCHAIN_EXTERNAL_WASI_SDK_PKGDIR)/wasi-stubs/* \
		$(STAGING_DIR)/include/wasm32-wasi/
	$(TOOLCHAIN_EXTERNAL_INSTALL_WRAPPER)
endef

define TOOLCHAIN_EXTERNAL_WASI_SDK_INSTALL_TARGET_CMDS
endef
