#!/usr/bin/env bash

set -e

. $(dirname $0)/post-process-helpers

# Parse our options
while getopts "n:g:o:" OPT; do
        case "${OPT}" in
        g)  gomod_init="${OPTARG}";;
        o)  output="${OPTARG}";;
        n)  base_name="${OPTARG}";;
        :)  error "option '%s' expects a mandatory argument\n" "${OPTARG}";;
        \?) error "unknown option '%s'\n" "${OPTARG}";;
        esac
done

# Already vendored tarball, nothing to do
if tar tf ${output} | grep -q "^[^/]*/vendor" ; then
	exit 0
fi

unpack ${base_name} ${output}

# Do the Go vendoring
pushd ${base_name} > /dev/null
# modcacherw option leaves directories in the module cache at their default
# permissions rather than making them read-only.
if [ ! -f go.mod ] && [ -n "${gomod_init}" ]; then
    go mod init -modcacherw ${gomod_init}
fi
go mod vendor -modcacherw -v
popd > /dev/null

repack ${base_name} ${output}
