#!/usr/bin/env bash

set -e

. "${0%/*}/helpers"

# Parse our options
while getopts "n:o:" OPT; do
    case "${OPT}" in
    o)  output="${OPTARG}";;
    n)  base_name="${OPTARG}";;
    :)  error "option '%s' expects a mandatory argument\n" "${OPTARG}";;
    \?) error "unknown option '%s'\n" "${OPTARG}";;
    esac
done

# Already vendored tarball, nothing to do
if tar tf "${output}" | grep -q "^[^/]*/vendor" ; then
    exit 0
fi

post_process_unpack "${base_name}" "${output}"

# Initialize go.mod if it doesn't exist
# This tells the Go compiler the module import path and language version.
# go1.19 is a reasonable default language version to use here.
if [ ! -f go.mod ]; then
    printf "module ${BR_GOMOD}\n\ngo 1.19\n" > go.mod
fi

# Do the Go vendoring
pushd "${base_name}" > /dev/null

go mod vendor -v -modcacherw
popd > /dev/null

post_process_repack $(pwd) "${base_name}" "${output}"
